# tasks file
---
- name: configuration | warn or fail  # noqa: ignore-errors
  ansible.builtin.fail:
    msg: "haproxy_global_nbproc is deprecated"
  ignore_errors: "{{ haproxy_version is version('2.5', '<') }}"
  when:
    - haproxy_version is version('2.3', '>=')
    - haproxy_global_nbproc > 1
  tags:
    - haproxy-configuration-warn-or-fail

- name: configuration | update file
  ansible.builtin.template:
    src: "{{ haproxy_conf_template }}"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0640
    validate: 'haproxy -f %s -c'
    backup: "{{ haproxy_backup_config | default(False) }}"
  notify: restart haproxy
  tags:
    - haproxy-configuration-update-file
