# handlers file
---
- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: "{{ haproxy_restart_handler_state }}"
  when: service_default_state | default('started') == 'started'
